name: trackml
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pandas
  - matplotlib
  - jupyter
  - nbconvert
  - uproot
  - scipy
  - tqdm
  - scikit-learn
  - pip:
    - mlflow
    - https://download.pytorch.org/whl/cu110/torch-1.7.1%2Bcu110-cp37-cp37m-linux_x86_64.whl
    - https://download.pytorch.org/whl/cu110/torchvision-0.8.2%2Bcu110-cp37-cp37m-linux_x86_64.whl
    - https://pytorch-geometric.com/whl/torch-1.7.0+cu110/torch_cluster-1.5.8-cp37-cp37m-linux_x86_64.whl
    - https://pytorch-geometric.com/whl/torch-1.7.0+cu110/torch_scatter-2.0.5-cp37-cp37m-linux_x86_64.whl
    - https://pytorch-geometric.com/whl/torch-1.7.0+cu110/torch_sparse-0.6.8-cp37-cp37m-linux_x86_64.whl
    - https://pytorch-geometric.com/whl/torch-1.7.0+cu110/torch_spline_conv-1.2.0-cp37-cp37m-linux_x86_64.whl
    - git+https://github.com/jmduarte/pytorch_geometric.git@add-trackml-to-dataset
    - git+https://github.com/LAL/trackml-library
    - kaggle

